### ISSUE TITLE
getting error ERR_TOO_MANY_REDIRECTS 

### ISSUE THREAD

**Issue by 4bd3ll4z1z** [microsoftgraph/msgraph-sample-phpapp#10]
I'm getting error ERR_TOO_MANY_REDIRECTS when trying to log in, the request return statut 302 in an endless loop, it worked fine yesterday, today it's not working anymore, i tried it in private tab, clear cache and cookies still getting error

**Comment by jasonjoh** [comment]
I do not reproduce this. Are you still having the problem? It may have been an intermittent issue with Azure AD.

**Comment by 4bd3ll4z1z** [comment]
I'm still having the problem, I recreate the project from scratch 3 times and still getting the problem everytime

**Comment by jasonjoh** [comment]
What sort of account are you logging in with? Is it an Azure AD account, or a Microsoft account (like outlook.com, etc.)?

**Comment by jasonjoh** [comment]
Closing due to no response.
