### ISSUE TITLE
Invalid Link in 06-completed.md

### ISSUE THREAD

**Issue by OPVL** [microsoftgraph/msgraph-sample-phpapp#13]
Hi,

Just a small issue, when you get the final .md file you cannot view the overview as that link doesn't point to anything. The resource probably moved or if it's available anymore this should probably be updated to reflect that.

https://github.com/microsoftgraph/msgraph-training-phpapp/blob/master/graph/overview
**TL;DR: ^^ doesn't exist anymore ^^**

**Comment by jasonjoh** [comment]
Thanks for reporting. The link should go to https://docs.microsoft.com/graph/overview. It's set as a relative link because that file gets published to https://docs.microsoft.com/graph/tutorials/php?tutorial-step=5, where the link works :).
