### ISSUE TITLE
No access token has been provided. in CalendarController

### ISSUE THREAD

**Issue by bitrevo** [microsoftgraph/msgraph-sample-phpapp#14]
I am following the tutorial and found that the "No access token has been provided." error from Laravel in the Calendar chapter.

The Calendar controller will get the access token and set it in the graph api.
```php
        // Get the access token from the cache
        $tokenCache = new TokenCache();
        $accessToken = $tokenCache->getAccessToken();

        // Create a Graph client
        $graph = new Graph();
        $graph->setAccessToken($accessToken);
```

However, if the session never expired and never refresh the token, the `session('refreshToken')` valuw will be null and the function `getAccessToken()` returning the empty string to the CalendarController.

```php
public function getAccessToken() {
  // Check if tokens exist
  if (empty(session('accessToken')) ||
      empty(session('refreshToken')) ||
      empty(session('tokenExpires'))) {
    return '';
  }
```

Is this a bug or I missed some steps?

**Comment by jasonjoh** [comment]
Sorry to hear you're having trouble. Can you explain your repro scenario? I'm not sure I'm getting the full picture. You should always have a refresh token. Are you including `offline_access` in your `OAUTH_SCOPES`?

**Comment by bitrevo** [comment]
> Sorry to hear you're having trouble. Can you explain your repro scenario? I'm not sure I'm getting the full picture. You should always have a refresh token. Are you including `offline_access` in your `OAUTH_SCOPES`?

Yes, that's the issue. Now I included `offline_access` in the scopes and it works now. Thanks.
