### ISSUE TITLE
Getting Invalid auth state: The provided auth state did not match the expected value

### ISSUE THREAD

**Issue by adajusr** [microsoftgraph/msgraph-sample-phpapp#17]
Hi!
I'm doing the Tutorial and when I sign in, the Php App shows me a welcome message with my name, but also, before the welcome message, appears "Invalid auth state" -"The provided auth state did not match the expected value".  

![image](https://user-images.githubusercontent.com/20147413/66674174-80c44b00-ec1f-11e9-8172-e89c80bfc254.png)

Looking at the code, this message comes from _callback()_ function from  _AuthController_.  The message shows up because _sesession('oauthState')_ is null.

So..... at the same controller  _AuthController_, when signing in with function _signin()_, the value of 
_sesession('oauthState')_  is set, is not null. But later,  at the callback it has changed to null....

Please help....

**Comment by jasonjoh** [comment]
Are you certain it's null, or could it be there's a mismatch? It's interesting that you get your name there even with the error. If you hit the error case it shouldn't execute the code to get your user details from Graph.

You might compare your code with the completed project here: https://github.com/microsoftgraph/msgraph-training-phpapp/tree/master/Demos/03-add-msgraph

**Comment by adajusr** [comment]
Thanks for answering! I deleted the entire project and just copied the completed tutorial and it worked! Now I'm able to sign in and see my calendar, which is what the Php App should do.  But after testing several times, I noticed that I'm able to get the same error message,  even though the calendar keeps displaying ok, .... And I'm wondering if this is only happening to me... These are the steps to see the error message:
1. Login in the first time. Notice that when I login for the first time the screen that I see is
![image](https://user-images.githubusercontent.com/20147413/66854632-3a4d5400-ef71-11e9-87a3-d0fbbce69e38.png)


2. Enter password.
3. The app redirects me to The PHP App, and I'm able to see my calendar perfectly.
4.  Then Sign out
5. Then click on the "Click here to sign in" button
6. This time the Login in page looks different, because is remembering my account, and also trying to find out if there are more accounts...So it takes some seconds to figure it out.  At this point I have to options (1) Wait until no more accounts found and automatically sign in, or ... (And here is when the error comes)  (2) Click on my account.

![image](https://user-images.githubusercontent.com/20147413/66855920-acbf3380-ef73-11e9-9c77-c4cdfe98cfdd.png)

7. I get on the Php App, I can see the error message... and  if I click on Calendar, it displays perfectly. 


This time the issue is not with signing in or displaying the calendar which is the purpose of this tutorial, I think it is more about signing out properly, so ... I'm just gonna wait for your opinion and then I will close the issue. Thank you so much for your time and help.

**Comment by jasonjoh** [comment]
Interesting. So if you click your account while it still says "Finding more accounts..." you reproduce, but if you wait it doesn't happen?

**Comment by adajusr** [comment]
That's right! No error if I wait.

**Comment by jasonjoh** [comment]
Ok. I'm glad your unblocked but I'm going to see if I can reproduce this.

**Comment by jasonjoh** [comment]
I can reproduce this as well. It seems that in this case, Azure redirects back to the app twice. The first time around, we remove the state from the session (`$request->session()->forget('oauthState');`), then the second time around it triggers the error due to `$expectedState` being empty.

So it looks like the auto-sign in gets triggered as well as the explicitly-clicked sign-in, which is arguably a bug on Azure's side (not sure if they would agree, but it looks that way). I'll report this to them and see what they say.

One way to mitigate this might be to just silently ignore requests to the callback if there is no expected state in the session. Basically if the app isn't expecting a callback, just drop it :).

**Comment by adajusr** [comment]
Thank you so much jasonjoh. I hope Microsoft answers soon.  I will add the changes to the Php App.
