### ISSUE TITLE
Tutorial without the bloatware?

### ISSUE THREAD

**Issue by PREngineer** [microsoftgraph/msgraph-sample-phpapp#20]
Is it possible to get this information without all of the Laravel bloatware?

I would love to be able to learn how to use this but I can't understand where the actual code resides within all the bloatware added by Laravel.

A simple and plain PHP project would be greatly appreciated.

Issues:

1. Laravel's web server doesn't use SSL because it uses the native PHP dev server.

This means that it simply doesn't work because Azure doesn't work with plain HTTP in its response.

2. This project doesn't build with a plain installation of IIS and PHP 7.3.7. because it is written to work with Laravel's routing and structure.

**Comment by jasonjoh** [comment]
Thanks for your feedback. We are currently discussing providing simpler versions of some of our web-based tutorials (PHP, Ruby, Python, etc.). I can't make any promises, but it is under consideration.

Laravel is definitely not required for this :)

**Comment by katalin2003** [comment]
Hello @jasonjoh.
Sorry for reopening this but is there a place where progress or announcement of this new way will be made?
Thank you

**Comment by jasonjoh** [comment]
Any new tutorials we add would be listed at https://docs.microsoft.com/graph/tutorials.
