### ISSUE TITLE
Is there any exception handling method?

### ISSUE THREAD

**Issue by dennis1** [microsoftgraph/msgraph-sample-phpapp#21]
Hi,

I have gone through the example code and I noticed that there are only try functions but never an exception catching function? Will it throw any exceptions at all?

I am using the createRequest function and I encountered errors but there is no exception.

Regards,

Dennis

**Comment by jasonjoh** [comment]
@dennis1 can you provide an example of what you mean? I use try/catch in two files, but I don't have any try without a catch.

**Comment by jasonjoh** [comment]
Closing this issue due to no reponse.

**Comment by dennis1** [comment]
Sorry I think I posted the wrong issue, I was looking at one of your three demo examples link which is https://docs.microsoft.com/en-gb/graph/tutorials/php?tutorial-step=3, it is actually for Microsoft. It shows the example of how to use 'createRequest', I was using this function but couldn't get any error or exception messages or code. Nevermind I am not in that project anymore.
