### ISSUE TITLE
Error trying this tutorial and it's throwing this error

### ISSUE THREAD

**Issue by Hassan-ssan** [microsoftgraph/msgraph-sample-phpapp#228]
I have followed every step correctly
After clicking sign in this error appears:
GuzzleHttp \ Exception \ RequestException
PHP 8.3.2
9.52.16
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://login.microsoftonline.com/common/oauth2/v2.0/token

**Comment by jasonjoh** [comment]
There is some setup required for PHP to allow it to make web requests. Try the solutions from: https://www.php.net/manual/en/curl.configuration.php

Specifically, you need to download cacert.pem and set `curl.cainfo` in your php.ini.
