### ISSUE TITLE
How to access $count=true result ?

### ISSUE THREAD

**Issue by davewillyp** [microsoftgraph/msgraph-sample-phpapp#27]
Is there a way to return the raw JSON instead of converting it to an object?
Once converted to a specific object you lose the $count result.

**Comment by jasonjoh** [comment]
As far as I can tell the SDK always returns a strongly-typed object. The request object does have a `guzzleClient` property that you could probably use to do the HTTP request yourself though.

**Comment by davewillyp** [comment]
Thanks, I've managed to modify the GraphResponse.php to return the full body, rather than wrapping it in a class.
