### ISSUE TITLE
getDisplayName() is not work for core php

### ISSUE THREAD

**Issue by danish-manzoor** [microsoftgraph/msgraph-sample-phpapp#39]
Hi sir 
Hope you are doing well.I read the documentation : https://docs.microsoft.com/en-us/graph/tutorials/php
and implement the PHP apps with Microsoft Graph.
Everything is right but a issue come when i send the get request using graph then it returned Microsoft\Graph\Http\GraphResponse Object when i use the method getDisplayName() it return Call to undefined method Microsoft\Graph\Http\GraphResponse::getDisplayName().
I just need to get the name and email.

So kindly help me in this regard
I shall be very thankful to you.Please🙏

**Comment by jasonjoh** [comment]
`getDisplayName` would not apply to `GraphResponse`. You need to have a `Microsoft\Graph\Model\User` object, which you get by calling `->setReturnType(Model\User::class)` like:

```
$user = $graph->createRequest('GET', '/me?$select=displayName,mail,mailboxSettings,userPrincipalName')
    ->setReturnType(Model\User::class)
    ->execute();
```
