### ISSUE TITLE
How do you redirect a user if they reach a URL and do not have a valid access token

### ISSUE THREAD

**Issue by jmiertschin** [microsoftgraph/msgraph-sample-phpapp#4]
If a user has not logged in using their Microsoft credentials and attempts to go to the url http://localhost:8000/calendar by directly typing the URL into the address bar, the tutorial simply throws an error message saying `No access token has been provided`.

What would be the best way to redirect to another URL when there is not a valid access token? For example, what if we wanted to redirect the user back to `http://localhost:8000`?

![screen shot 2018-12-05 at 5 27 01 pm](https://user-images.githubusercontent.com/16867812/49555001-fef2eb00-f8b2-11e8-82c0-aa1cafff635b.png)

**Comment by jasonjoh** [comment]
This sample uses [Laravel](https://laravel.com/docs/5.7/redirects#redirecting-named-routes), so you would use their APIs to handle a redirect. In a simple fashion, you could test if the `$accessToken` variable is null or empty, and if so redirect like:

```
return redirect('/home');
```

**Comment by jmiertschin** [comment]
Thanks @jasonjoh.

Do you have recommendations about where to place the redirect code?  I realize that you could place code in each Controller like this:

```
// Get the access token from the cache
$tokenCache = new TokenCache();
$accessToken = $tokenCache->getAccessToken();

if ( empty($accessToken) ) {
   return redirect('/');
}
```

To place the that same redirect code in each Controller seems repetitive.  However, if I try to add a similar redirect command in the function `getAccessToken()` it results in errors.  For example: I added the below code to `getAccessToken()` in the file`./app/TokenStore/TokenCache.php` and I still get the error `No access token has been provided.`.

```
public function getAccessToken() {
    
    if (empty(session('accessToken'))) {
      redirect ('/');
    }

// all the code provided by Microsoft goes below 
```

So the question is, do you have to add code to each controller to institute a redirect or can you do it from the `TokenCache.php` and if you can add code to the `TokenCache.php` file, can you give some guidance on what that code should be?  Thanks.

**Comment by noahheck** [comment]
Since this project is based on Laravel, you could accomplish what you're attempting by putting the check in a Middleware class. The middleware runs on each request, so you wouldn't need to add the `accessToken` check in each controller. It could look something like this

```php
namespace App\Http\Middleware;

use Closure;

class VerifyAccessToken
{
    public function handle($request, Closure $next)
    {
        if (empty(session('accessToken')) {
            return redirect('/home');
        }
        
        return next($request);
    }
}
```

Then, you just need to register your middleware with the `Kernel` class.

```php
// app/Http/Kernel.php
protected $middlewareGroups = [
    'web' => [
    // [...]
        \App\Http\Middleware\VerifyAccessToken::class,
    // [...]
```

You can find out more in the Laravel documentation: https://laravel.com/docs/5.7/middleware

**Comment by jasonjoh** [comment]
Thanks @noahheck
