### ISSUE TITLE
Impossible authentication (TOO_MANY_REDIRECT)

### ISSUE THREAD

**Issue by askorad** [microsoftgraph/msgraph-sample-phpapp#40]
I met issues with the signin method. It worked well at th beginning and then stopped working (TOO_MANY_REDIRECTS)....

By investigation, I realised that the array given for initializing the OAuth client was empty. Actually, the .env keys where not read. This is a problem that I already met in other Laravel projects : env(...) function does not work after the config is cached.

This can be solved declaring these variables in the **config/app.php** file and then calling them in the controller with the global **config** helper.

In our case, add these lines in the **config/app.php** file :

    /*
    |--------------------------------------------------------------------------
    | Microsoft OAUTH
    |--------------------------------------------------------------------------
    */
    'clientId'                => env('OAUTH_APP_ID'),
    'clientSecret'            => env('OAUTH_APP_PASSWORD'),
    'redirectUri'             => env('OAUTH_REDIRECT_URI'),
    'urlAuthorize'            => env('OAUTH_AUTHORITY').env('OAUTH_AUTHORIZE_ENDPOINT'),
    'urlAccessToken'          => env('OAUTH_AUTHORITY').env('OAUTH_TOKEN_ENDPOINT'),
    'scopes'                  => env('OAUTH_SCOPES'),

In the **AuthController.php** file, initialize the OAuth client this way :

        // Initialize the OAuth client
        $oauthClient = new \League\OAuth2\Client\Provider\GenericProvider([
            'clientId'                => config('app.clientId'),
            'clientSecret'            => config('app.clientSecret'),
            'redirectUri'             => config('app.redirectUri'),
            'urlAuthorize'            => config('app.urlAuthorize'),
            'urlAccessToken'          => config('app.urlAccessToken'),
            'urlResourceOwnerDetails' => '',
            'scopes'                  => config('app.scopes'),
        ]);

Then, run the command  **php artisan config:clear**

I hope this can help

**Comment by jasonjoh** [comment]
Thanks for the suggestion. I'll look at incorporating this into the next update.

**Comment by jasonjoh** [comment]
Update: I don't reproduce with PHP8 and Laravel 8. I dug through the Laravel docs and I think this is expected.

From [Configuration Caching](https://laravel.com/docs/8.x/configuration#configuration-caching):

> To give your application a speed boost, you should cache all of your configuration files into a single file using the `config:cache` Artisan command. This will combine all of the configuration options for your application into a single file which can be quickly loaded by the framework.
>
> You should typically run the `php artisan config:cache` command as part of your production deployment process. **The command should not be run during local development as configuration options will frequently need to be changed during the course of your application's development.**
>
> If you execute the `config:cache` command during your deployment process, you should be sure that you are only calling the `env` function from within your configuration files. **Once the configuration has been cached, the .env file will not be loaded and all calls to the `env` function will return null.**

Did you previously run the `config:cache` command? That would explain the problem.

In any event, I tested this by making your suggested change and running *without* calling `config:cache` and it still seems to work fine, so I think this change will avoid hitting the problem once you try to move to production.
