### ISSUE TITLE
error 404; Not found - after clicking step 3 button in quick start example

### ISSUE THREAD

**Issue by letzfets** [microsoftgraph/msgraph-sample-phpapp#44]
### Where did you get the code?
Actually, the issue is, that I am NOT getting the code!
- [ ] Downloaded from GitHub
- [ X] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [ ] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

### Describe the bug

After successfully generating the app secret and entering it in step 2 here
[Microsoft Graph Quick Start](https://developer.microsoft.com/en-us/graph/quick-start?appID=9da416fe-80fe-46fc-aae7-1cb020d267d9&appName=My%20PHP%20App&redirectUrl=http://localhost:8000/callback&platform=option-php)
I press the button below step 3:
<img width="419" alt="image" src="https://user-images.githubusercontent.com/44865639/101833938-f4225f00-3b39-11eb-8a9d-f4569e305866.png">

which produces an error 404: Not Found.

### To Reproduce

see above

### Expected behavior

I expected to get the quick start code!

### Screenshots

<img width="194" alt="image" src="https://user-images.githubusercontent.com/44865639/101834310-7c086900-3b3a-11eb-8ac9-c59fcedc8d76.png">

### Desktop

- iOS
- safari
- version 14.01

**Comment by jasonjoh** [comment]
Hi @letzfets. The issue is that in Safari, the quick start tool just directs you to this GitHub repository to download the latest code as a ZIP. You're getting a 404 because it's pointing at the "master" branch, which has been renamed to "main".

Sorry for the confusion: I've reported this issue to the quick start team to get fixed. In the meantime you can download or clone this repository to get the code.

**Comment by letzfets** [comment]
@jasonjoh : agree: it's not a major showstopper and the user can easily play with the git code here. I haven't seen that it is the change from "master" to "main", that broke the link - but makes really much sense! Thx for clarifying! 🙏 Cheers🍻
