### ISSUE TITLE
Action App\Http\Controllers\CalendarController@getNewEventForm not defined.

### ISSUE THREAD

**Issue by endersaka** [microsoftgraph/msgraph-sample-phpapp#46]
### Where did you get the code?

- [0] Downloaded from GitHub
- [0] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [1] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

### Describe the bug

The exeption rises following step 4 of the tutorial: [Get a calendar view](https://docs.microsoft.com/en-us/graph/tutorials/php?tutorial-step=4), paragraph "Display the results".

```
InvalidArgumentException
Action App\Http\Controllers\CalendarController@getNewEventForm not defined. (View: /path_to_project_dir/resources/views/calendar.blade.php) 
```

It is caused by this line (in my case line 6) in the `resources/views/calendar.blade.php` source file.

```
<a class="btn btn-light btn-sm mb-3" href={{action('CalendarController@getNewEventForm')}}>New event</a>
```

### To Reproduce

Follow the tutorial until "Display the results" paragraph, included.

### Expected behavior

Refreshing the browser view/tab should display calendar events list instead of the exception.

The route `Route::get('/calendar/new', 'CalendarController@getNewEventForm');` should be added before "Display the results" paragraph and not in the next step (step 5) of the tutorial.

### Screenshots

-

### Desktop

- OS: MacOS Sierra 10.12.6
- Browser: Firefox
- Version: 84.0.1 (64-bit)
- Apache 2.4.46
- PHP 7.4.10

### Dependency versions

```json
    "require": {
        "php": "^7.3|^8.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "laravel/framework": "^8.12",
        "laravel/tinker": "^2.5",
        "league/oauth2-client": "^2.6",
        "microsoft/microsoft-graph": "^1.25"
    },
    "require-dev": {
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^0.0.5",
        "mockery/mockery": "^1.4.2",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3.3"
    },
```

### Additional context

-

**Comment by jasonjoh** [comment]
Thanks for reporting. I'll get this fixed ASAP.
