### ISSUE TITLE
Can you read the list of AD users?

### ISSUE THREAD

**Issue by GuillermoFarias** [microsoftgraph/msgraph-sample-phpapp#5]
sorry if it is not the right place to ask, but he found 100 libraries with 100 different functionalities, is it possible in this example to list the users of the domain to have the IDs, and thus validate with the users of another bd?

**Comment by jasonjoh** [comment]
With this sample as-is, no, you cannot. It is certainly possible in Microsoft Graph, but of course requires admin privileges. See https://docs.microsoft.com/graph/api/user-list?view=graph-rest-1.0
