### ISSUE TITLE
when logging in with org tennent i get this error GuzzleHttp\Exception\ClientException

### ISSUE THREAD

**Issue by bluenun34** [microsoftgraph/msgraph-sample-phpapp#55]
hi I have followed the tutorial and I'm getting this error when I try to login with my organizations azure ad

 _Client error: `GET https://graph.microsoft.com/v1.0/me?$select=displayName,mail,mailboxSettings,userPrincipalName` resulted in a `403 Forbidden` response: { "error": { "code": "UnknownError", "message": "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<htm (truncated...)_

when I log in with my personal Microsoft account all seem fine and it works as expected. I think it might have something to do with the API permissions for the owned app in azure ad, also how would I limit this to only allow logins for my organizational tenet only and not logins for personal accounts. thank you in advance for any help I'm new to the graph environment and laravel also please bear with me as it might take a bit of explaining for me to understand

**Comment by jasonjoh** [comment]
403 usually means that the access token doesn't have the needed scopes, which for this would be `User.Read` and `MailboxSettings.Read`. I'd start by printing out your access token, then heading to https://jwt.ms to parse it. The `scp` claim shows what scopes are there.

To limit logins to just your org, two things are needed. First, when you register the application in Azure, you would select that option. Second, you need to replace `common` in the following line of your .env file with your tenant ID.

https://github.com/microsoftgraph/msgraph-training-phpapp/blob/992a95515c151411cb764c57a4edc958f0d7e6ca/demo/graph-tutorial/example.env#L55

**Comment by bluenun34** [comment]
thank you so much I finally got it working I enabled the user.read and mailbox settings.read also we are still using an on-prem exchange in a non-hybrid setup so getting calendar details didn't work so I removed all mentions to fetching calendar settings and it worked

**Comment by jasonjoh** [comment]
Ah yes that would explain it. Your mailbox needs to be in Exchange Online for Graph to be able to access it. Glad you got it working though!
