### ISSUE TITLE
Sign out not clearing or removing token data from session.

### ISSUE THREAD

**Issue by starthecode** [microsoftgraph/msgraph-sample-phpapp#56]
### Where did you get the code?

- [ ] Downloaded from GitHub
- [ ] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [ ] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

### Describe the bug

When we click on sign out, its not clear access token, and when we again sign in its not ask showing credentials window and direct giving login to session user.

I have also calling session flush fucntion from signout function.

like - 

    Session::forget('_token');
    session()->forget('_token');
but its not working.

### To Reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

### Expected behavior

Sign out must clear session data but its skip token in session as it is. 

### Desktop

- PHP 8 Laravel 8
- Browser Chrome
- Version Latest

### Dependency versions

- Authentication library (MSAL, etc.) version:
- Graph library (Graph SDK, REST library, etc.) version:

**Comment by jasonjoh** [comment]
@starthecode There is no `_token` in the sample. Are you using an older version maybe? I don't reproduce this with current code. The `signout` function in `AuthController` calls the following function to clear the cache:

https://github.com/microsoftgraph/msgraph-training-phpapp/blob/992a95515c151411cb764c57a4edc958f0d7e6ca/demo/graph-tutorial/app/TokenStore/TokenCache.php#L19-L26

**Comment by starthecode** [comment]
But above methods not working. When we click on sign in again its direct go to user dashboard without asking credentials screen. there is no changed in code and i am using your latest repo.

**Comment by jasonjoh** [comment]
Well keep in mind that all that code does is remove the tokens from the session. Your browser may still be keeping your credentials - for example, if you say yes to this prompt:

![image](https://user-images.githubusercontent.com/8966342/113708200-ef685480-96ae-11eb-93c5-94d05fd26e65.png)

In that case, when you sign out, the server *does* forget all of your tokens, but when you click **Sign In** again in your browser, the browser has enough information locally to pass to the authorization endpoint that it doesn't need to prompt you again for your password.

If you want to sign out of the browser, you can redirect the browser to the `end_session_endpoint`. Details are in the [Microsoft identity docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#send-a-sign-out-request).

**Comment by starthecode** [comment]
This i know, I never click on yes, but its still happening. can you check at ur side if that happening with you too.

**Comment by starthecode** [comment]
Here some screenshot, when i click on sign in again after sign out - 

![image](https://user-images.githubusercontent.com/49548791/113970897-5aec2680-9855-11eb-9b7b-ad5cfcb69909.png)

![image](https://user-images.githubusercontent.com/49548791/113970925-68091580-9855-11eb-9703-5b4754d0d4bf.png)

then its direct in to dashboard - 

![image](https://user-images.githubusercontent.com/49548791/113970960-7820f500-9855-11eb-86e3-ed2e75d059be.png)

**Comment by starthecode** [comment]
Above 3 screens only for sign in, no credentials screen till i go and clear all browser history.

**Comment by starthecode** [comment]
So how can i implement - end_session_endpoint ? any suggestions ?

**Comment by jasonjoh** [comment]
Yes, that's expected behavior if you don't do a full signout via end_session_endpoint. It's still redirecting to login.microsoftonline.com, but there's enough info in the browser session to authenticate you.

You should be able to simply do something like this:

```
$endSessionUrl = 'https://login.microsoftonline.com/common/oauth2/v2.0/logout?
post_logout_redirect_uri=http%3A%2F%2Flocalhost%3A8000';
return redirect()->away($endSessionUrl);
```

**Comment by starthecode** [comment]
Its working fine now. Thanks

![image](https://user-images.githubusercontent.com/49548791/119475866-27188200-bd6b-11eb-8a00-59d90de0d05d.png)
