### ISSUE TITLE
Getting "invalid_client" error

### ISSUE THREAD

**Issue by marcohorstmann** [microsoftgraph/msgraph-sample-phpapp#6]
Hi,
I just tried to implement your tutorial but it seems that I get an error "invalid_client".
`:\xampp\htdocs\vendor\league\oauth2-client\src\Provider\GenericProvider.php 
    protected function getScopeSeparator()
    {
        return $this->scopeSeparator ?: parent::getScopeSeparator();
    }
 
    /**
     * @inheritdoc
     */
    protected function checkResponse(ResponseInterface $response, $data)
    {
        if (!empty($data[$this->responseError])) {
            $error = $data[$this->responseError];
            if (!is_string($error)) {
                $error = var_export($error, true);
            }
            $code  = $this->responseCode && !empty($data[$this->responseCode])? $data[$this->responseCode] : 0;
            if (!is_int($code)) {
                $code = intval($code);
            }
            **throw new IdentityProviderException($error, $code, $data);**
        }
    }
 
    /**
     * @inheritdoc
     */
    protected function createResourceOwner(array $response, AccessToken $token)
    {
        return new GenericResourceOwner($response, $this->responseResourceOwnerId);
    }
}
 `

**Comment by marcohorstmann** [comment]
It seems that the new portal MS wants to use is not working. The Application Registration Portal will be closed but creating an app in Azure Portal seems not to work with this code. No idea what the problem is

**Comment by jasonjoh** [comment]
@marcohorstmann I'm actually in the process of updating this to use the new Azure Portal experience. I'll update here once I've updated it.

**Comment by jasonjoh** [comment]
Updated instructions are in now (see #7). Did you register in the portal using the "preview" app registration experience? If not, that might be the problem. The "old" app registration tool in the Azure portal isn't compatible with the new Azure Oauth endpoints (v2).

**Comment by jasonjoh** [comment]
Closing this due to no response. Let me know if you still need help.
