### ISSUE TITLE
Get access without a user

### ISSUE THREAD

**Issue by Giudice** [microsoftgraph/msgraph-sample-phpapp#61]
Hey,

First of all, thanks for this guide which is really a great way to start with ms graph
Is there a version of it to integrate the functionality of a no-user connection ?

Thank you

**Comment by jasonjoh** [comment]
No, we don't have an app-only version of this PHP tutorial. https://oauth2-client.thephpleague.com/usage/ shows how to use the client credentials grant to request an access token. Details on how to configure your app registration can be found at https://docs.microsoft.com/graph/auth-v2-service.

**Comment by Giudice** [comment]
Thanks for the tip
