### ISSUE TITLE
Question: How do I update a calendar event?

### ISSUE THREAD

**Issue by CarlAtIssl** [microsoftgraph/msgraph-sample-phpapp#62]
Hi

Using your code:-

[https://docs.microsoft.com/en-us/graph/tutorials/php?tutorial-step=1](url)

I have managed to create an event in my outlook calendar, for identification purposes, I place our appointment_id into transactionId - I don't save the ID returned by your API - firstly - should I?

Secondly, does this plugin allow the following:-

Update an existing event and if so, is there an example or documentation?
Delete an existing event and if so, is there an example or documentation?

Thirdly, do you have, or is there, any examples of working with recurring events, as above really, to be able to create, update, delete the series?

If this is the wrong place to ask, can you please provide a link to where is best to ask the above?

Kind regards in advance.
Carl.

**Comment by jasonjoh** [comment]
- You should save the ID returned by the API if you want to modify or delete it later - you'll need that ID as part of the API call. Of course if you're setting a custom value in `transactionId` you could find the appointment again later and get the `id` that way.
- This sample does not do update or delete, but you could easily add this. [Update event](https://docs.microsoft.com/graph/api/event-update?view=graph-rest-1.0&tabs=http), [Delete event](https://docs.microsoft.com/graph/api/event-delete?view=graph-rest-1.0&tabs=http)
- Recurring events use the same APIs to create, update, delete. You just need to fill in the recurrence properties. More information [here](https://docs.microsoft.com/graph/outlook-schedule-recurring-events?view=graph-rest-1.0)

Typically the best place to ask questions about Microsoft Graph is on [Microsoft Q&A](https://docs.microsoft.com/answers/products/graph).
