### ISSUE TITLE
Updating an event getting error 'The specified object was not found in the store'

### ISSUE THREAD

**Issue by CarlAtIssl** [microsoftgraph/msgraph-sample-phpapp#63]
Hi

In my Laravel system, we have a diary and can create single item diary appointments and recurring. When I edit an appointment that is a single item, the code works, when I then edit a recurring sequence, the update fails.

The code to do the update is:-

```
$response = $graph->createRequest('PATCH', '/me/events/' . $existing_appointment->MicrosoftID)
	->attachBody($newEvent)
	->setReturnType(Model\Event::class)
	->execute();
```

The exception error that is displayed on screen is
```
 Client error: `PATCH https://graph.microsoft.com/v1.0/me/events/{id}` resulted in a `404 Not Found` response: ◀
      {"error":{"code":"ErrorItemNotFound","message":"The specified object was not found in the store.","innerError":{"date":"2021-11-16T09:51:35","request-id":"{request_id}","client-request-id":"{client_request_id}"}}} ◀
```
I've removed the id's for security purposes.

Also, i've double checked the ID (by pulling the events from the calendar - using your test code) and the ID is exact!

Any idea why this error occurs?

Also, I've tried to DELETE the event and re-create a new one but the delete fails with the not found in store. BUT, I know it exists as my laptop displays it!

Thanks for any help in fixing this issue.
Regards
Carl.

**Comment by jasonjoh** [comment]
One thing to check is if you can use that ID in [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer) to do a `GET https://graph.microsoft.com/v1.0/me/events/{event-id}`. My only theory here is that the ID that you're seeing isn't the ID that goes out in the actual request. Maybe it's been truncated, maybe characters have changed case (IDs are case-sensitive), maybe there's a bug in the SDK that's encoding it wrong, etc..

**Comment by CarlAtIssl** [comment]
> One thing to check is if you can use that ID in [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer) to do a `GET https://graph.microsoft.com/v1.0/me/events/{event-id}`. My only theory here is that the ID that you're seeing isn't the ID that goes out in the actual request. Maybe it's been truncated, maybe characters have changed case (IDs are case-sensitive), maybe there's a bug in the SDK that's encoding it wrong, etc..

No, there is no difference between IDs from what I've stored in my db/appointment and to what is returned from your sample code. The only difference is that I use the above call and your demo uses '/me/calendarView?'

Any other thoughts?
Regards
Carl.

**Comment by jasonjoh** [comment]
To clarify: did it work in Graph Explorer?

The calls don't matter much here. `GET /me/calendarview` does expansion of recurring events, but the `id` of the returned events should always work with `GET /me/events/{event-id}`.

**Comment by CarlAtIssl** [comment]
Hi Jason,

No, I've not used Graph Explorer, I was trying it in my code. I'll see if I can get it working in graph explorer (not used before so will suss it out) and then back to you.

Regards
Carl.

**Comment by CarlAtIssl** [comment]
> To clarify: did it work in Graph Explorer?
> 
> The calls don't matter much here. `GET /me/calendarview` does expansion of recurring events, but the `id` of the returned events should always work with `GET /me/events/{event-id}`.

To clarify, I've tried the GET /me/events/{event-id} and it brings back ALL future appointments including the one I want, it looks to have a bug as it should only bring back 1 event.

This still doesn't answer why the PATCH won't update the event. Very frustrating!
Carl.

**Comment by CarlAtIssl** [comment]
Hi

I've changed some of my code and now I get a new error, the api call is:-

```
Client error: `PATCH https://graph.microsoft.com/v1.0/me/events/?id={id} ▶
      {"error":{"code":"ErrorInvalidRequest","message":"The OData request is not supported."}}
```
Any idea of what I've now done wrong?
Cheers
Carl.

**Comment by jasonjoh** [comment]
The format isn't right. The event ID isn't a query parameter, so `?id={id}` is causing your `ErrorInvalidRequest`. The correct format is `/me/events/{id}`.

> To clarify, I've tried the GET /me/events/{event-id} and it brings back ALL future appointments including the one I want, it looks to have a bug as it should only bring back 1 event.

There's definitely an issue here. Let's make sure we're on the same page by using Graph Explorer.

If you go to Graph Explorer, you should be able to run a `GET /me/events`:

![get-events](https://user-images.githubusercontent.com/8966342/142657033-2166c97a-7570-4c27-a5e7-3de63853d3df.png)

If you copy the `id` property of one of the returned events, you should be able to run a `GET /me/events/{copied-id}`. For example, in my screenshot above, I copy `AAMkADY0ZjM2ZWJlLTEwOGUtNGNiOS04MTFiLWE3Y2UwNjRiZDNiMQBGAAAAAACWRvY6Vjb0SabVPshsbtVRBwAtISQkTseOQLhQ9a0koD2UAAAAAAENAAAtISQkTseOQLhQ9a0koD2UAAD34e37AAA=`, so my query becomes:

```
GET /me/events/AAMkADY0ZjM2ZWJlLTEwOGUtNGNiOS04MTFiLWE3Y2UwNjRiZDNiMQBGAAAAAACWRvY6Vjb0SabVPshsbtVRBwAtISQkTseOQLhQ9a0koD2UAAAAAAENAAAtISQkTseOQLhQ9a0koD2UAAD34e37AAA=
```

![get-event-by-id](https://user-images.githubusercontent.com/8966342/142657066-67dcb7ef-582a-42da-8026-c84509e30473.png)

What does your `id` look like? If it doesn't look like mine, there's something wrong.

**Comment by CarlAtIssl** [comment]
Hi,

Ok, that worked, thanks for that.

Now, when I then do the following:-
```
$response = $graph->createRequest('PATCH', '/me/events/' . $existing_appointment->MicrosoftID)
	->attachBody($newEvent)
	->setReturnType(Model\Event::class)
	->execute();
```

I get an error:

```
Client error: `PATCH https://graph.microsoft.com/v1.0/me/events/AAMkADRmMTk5NjI2LTRlYzgtNDA2NS1iYjdlLTQwZTYyOWZjYWU0OQBGAAAAAABQ6uxL3ELGS7P64jB7yEKMBwCqSE0I2Mu-SKWuoLWKq1WYAAAAAAENAACqSE0I2Mu-SKWuoLWKq1WYAAOsinRgAAA=` resulted in a `400 Bad Request` response: ◀
      {"error":{"code":"ErrorInvalidRequest","message":"Your request can't be completed. ClientId/TransactionId is immutable and cannot be updated."}}
```

Can you assist in fixing this error?

Kind regards
Carl.

**Comment by CarlAtIssl** [comment]
Hi 

Thanks for the information, with your help, I now am able to create, update and delete everything.

Kind regards
Carl.
