### ISSUE TITLE
Create Calendar event - exclude organiser

### ISSUE THREAD

**Issue by CarlAtIssl** [microsoftgraph/msgraph-sample-phpapp#64]
Hi

When I create an event in the calendar (an appointment) and am creating it for another office 365 user, how to I set the attendees so that me (the creator) either doesn't see it in my calendar OR make me an optional attendee?

I've tried

```
$attendees[] = [
	'emailAddress' => [
		'address' => $staffOrganiser->StaffEmail,
	],
	'type' => 'optional',
	];
$staffAttendee = \UserHelpers::getStaffById($app_user->StaffID);
$attendees[] = [
	'emailAddress' => [
		'address' => $staffAttendee->StaffEmail,
	],
	'type' => 'required',
];
```

I've currently just set the attendees to

```
	$staffAttendee = \UserHelpers::getStaffById($app_user->StaffID);
	$attendees[] = [
		'emailAddress' => [
			'address' => $staffAttendee->StaffEmail,
		],
		'type' => 'required',
	];
```

I'd prefer NOT to show in the organisers calendar if the event is for another person!

Thanks for any and all help in advance
Carl.

**Comment by jasonjoh** [comment]
If you are creating it for another person, why are you creating it on *your* calendar? You should be creating it on their calendar if that's what your goal is. This would of course require that you have been given access to said user's calendar.

Any time a user creates an event on their calendar, they will always be the organizer and will always be included in the attendee list.
