### ISSUE TITLE
Question: How to fix ErrorException Undefined array key ""?

### ISSUE THREAD

**Issue by lnavarro-a2bhq** [microsoftgraph/msgraph-sample-phpapp#65]
I'm getting error with the Timezone part. How do I fix it? Thank you.

![image](https://user-images.githubusercontent.com/92632425/148578879-8b550921-3930-4032-b4b8-e74ed7838437.png)

**Comment by jasonjoh** [comment]
Looks like you may not have a timezone set in your Outlook settings, so the code that gets the timezone from Graph is getting an empty string. You can safeguard against this by changing this line:

https://github.com/microsoftgraph/msgraph-training-phpapp/blob/68bfcb823cf5b8c74e3c9ed47c630ccbf35bbbe4/demo/graph-tutorial/app/TokenStore/TokenCache.php#L15

To something like:

```php
'userTimeZone' => $user->getMailboxSettings()->getTimeZone() ? 'UTC'
```
