### ISSUE TITLE
Microsoft graph does not seem to return state

### ISSUE THREAD

**Issue by ShaydenV** [microsoftgraph/msgraph-sample-phpapp#68]
### Where did you get the code?

- [ ] Downloaded from GitHub
- [ ] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [x] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

### Describe the bug

The reply given after accessing 
```
//Line breaks are for readability only

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?
state={state}
&scope=openid%20profile%20offline_access%20user.read%20mailboxsettings.read%20calendars.readwrite
&response_type=code
&approval_prompt=auto
&redirect_uri=https%3A%2F%2{url}%2Fcallback
&client_id={clientID}
```

Contains only a code as shown
```
//Line breaks are for readability only
https://{url}/callback?
code={code}
```

As opposed to the expected
```
//Line breaks are for readability only
https://{url}/callback?
code={code}
&state={state}
```

This means that the 'Invalid auth state' error is generated
### To Reproduce

1. Follow tutorial up until the end of 'Add Azure AD authentication'
2. Deploy code to server with correct .env and redirect variables
3. Try to login

### Expected behavior

The user is logged in and their details are displayed.

### Desktop

- Server: VPS running Ubuntu 20.04 x64, Nginx 1.18.0, php 7.4.3
- OS: Windows 10, macOS12.1
- Browser: Firefox 96.0.3, Safari 15.2

### Additional context
I found this by seperating this check
```
if (!isset($providedState) || $expectedState != $providedState) {
      return redirect('/')
        ->with('error', 'Invalid auth state')
        ->with('errorDetail', 'The provided auth state did not match the expected value');
    }
```
Into
```
if (!isset($providedState)) {
      return redirect('/')
        ->with('error', 'Invalid auth state')
        ->with('errorDetail', 'No provided state');
    }
if ($expectedState != $providedState) {
      return redirect('/')
        ->with('error', 'Invalid auth state')
        ->with('errorDetail', 'The provided auth state did not match the expected value');
    }
```

**Comment by jasonjoh** [comment]
@ShaydenV sorry to hear you're having problems with the sample. Just to clarify, the OAuth flows are provided by the [Microsoft identity platform](https://docs.microsoft.com/azure/active-directory/develop/active-directory-v2-protocols).

I tried this just now and don't reproduce the behavior. I registered a test app registration with a redirect of `https://localhost:5001/auth`, then browsed to:

```
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?state=MyCoolStateValue
&scope=openid%20profile%20offline_access%20user.read%20mailboxsettings.read%20calendars.readwrite
&response_type=code
&approval_prompt=auto
&redirect_uri=https%3A%2F%2Flocalhost:5001%2Fauth
&client_id=0c7e22b4-a8cb-454b-b4bf-a148d618a0be
```

Once I logged in and consented, the browser redirected to:

```
https://localhost:5001/auth?code={code}
&state=MyCoolStateValue
&session_state=9b00d1be-3821-469f-8343-a9f00032617e
```

I wonder if your app isn't sending a state value at all. Can you check the `$authUrl` and see if it has a `state` query parameter?

**Comment by ShaydenV** [comment]
So I have verified the ``$authUrl`` is the same as the one that appears in my browser and it all seems the same and it follows the pattern that I showed above.

I am working on a non local server and within a subdomain if that is of any consequence

**Comment by jasonjoh** [comment]
Ok so to clarify, you do see `state` in the URL?

Does this happen when you run it on your local machine (using `http://localhost:8000`), or only when you deploy to a server?

**Comment by ShaydenV** [comment]
I have reviewed the latest URL batch and in all cases a ``state`` value exists in the URL

As far as I can tell it is not happening locally however I cannot test subdomains as adding one to ``http://localhost:8000`` is not allowed by the redirect URI restrictions.

**Comment by jasonjoh** [comment]
ok, so this may be an issue with your app registration itself. The tutorial only has you set `http://localhost:8000/callback` as a redirect URI. If you've deployed to a server, you'll need to add the server's hostname as an additional redirect. The exact URL to your `/callback` path on the server will have to be on the app registration.

**Comment by ShaydenV** [comment]
Yes I did cover that, the current redirect URI follows ``https://{subdomain}.{domain}/callback`` both in the ``.env`` file as well as in the Azure App Registration Redirect URI.

The ``web.php`` route also contains the following
```
Route::domain('{subdomain}.' . config('app.url'))->group(function (){
    Route::get('/signin', [AuthController::class, 'signin']);
    Route::get('/signout', [AuthController::class, 'signout']);
    Route::get('/callback', [AuthController::class, 'callback']);
    Route::get('/', [HomeController::class, 'home']);
});

**Comment by jasonjoh** [comment]
Can you check the network tab in your browser's dev tools (`F12`) to see what requests are coming and going?

You're going to want to enable the **Preserve log** option:

![image](https://user-images.githubusercontent.com/8966342/152406827-783f0b9a-761f-40d4-a48c-71ee723bec40.png)

You should see a request to the `/authorize` URL:

![image](https://user-images.githubusercontent.com/8966342/152407106-c249c37c-faba-4e2d-b980-de3870f0d75b.png)

And after signing in, there should be a request back to the `/callback` URL in the app:

![image](https://user-images.githubusercontent.com/8966342/152407248-78ac36a6-e94f-4730-8c89-472567755d61.png)

If you look at the `/callback` request, does it have the `state` and `session_state` parameters?

**Comment by ShaydenV** [comment]
So i have looked through and I do see a state in the `/callback` request

I have tried `$request->all()` and `$request->query()` and both have returned empty arrays

**Comment by ShaydenV** [comment]
Hello

So now that we found that I looked a bit further into Nginx not passing get variable and found that I had a incorrect config for passing that data. The way I had it configured was:
```
location / {
    try_files $uri $uri/ /index.php?query_string
}
```
Rather than
```
location / {
    try_files $uri $uri/ /index.php?$query_string
}
```
It is now fixed, thank you for your help and sorry for wasting your time

**Comment by jasonjoh** [comment]
No problem! I'm glad you were able to figure it out. Thanks for following up and providing the solution.
